# Generated by Django 2.2.1 on 2019-05-14 22:59

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190514_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='text',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')]),
        ),
    ]
