# Generated by Django 2.2.1 on 2019-05-14 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190514_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='text',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[\\w-]([\\w-\\s]*[\\w-])?$')]),
        ),
    ]
