# Generated by Django 2.2.1 on 2019-05-14 23:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190514_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='text',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[\\w\\-]([\\s\\w\\-]*[\\w\\-])?$')]),
        ),
    ]
