# Generated by Django 2.2.1 on 2019-05-14 23:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190514_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='text',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[\\s\\w\\-]*$', 'It only allows letters, numbers, whitespaces, underscores and hyphens.')]),
        ),
    ]
