# Generated by Django 2.2.1 on 2019-05-15 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190515_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='text',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[\\s\\w\\-]+$', 'It only allows letters, numbers, whitespaces, underscores or hyphens.')]),
        ),
    ]
